In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[2:6])

[3 4 5 6]


In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[::2]) #slicing with a step of 2
print(a[::3]) #slicing with a step of 3
print(a[::4]) #slicing with a step of 4

[1 3 5 7 9]
[1 4 7]
[1 5 9]


In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[::-1]) #reversing the array

[9 8 7 6 5 4 3 2 1]


In [8]:
#Slicing multi-dimensional array
import numpy as np
a=np.array(([1,2,3],[4,5,6,],[7,8,9]))
print(a[0:2,1:3])

[[2 3]
 [5 6]]


In [9]:
import numpy as np
a=np.array(([1,2,3],[4,5,6,],[7,8,9]))
print(a[:2,:1])

[[1]
 [4]]


In [16]:
import numpy as np
a=np.array(([1,2,3],[4,5,6,],[7,8,9]))
print(a[:,0])
print(a[0,:])
print(a[0:3:2])

[1 4 7]
[1 2 3]
[[1 2 3]
 [7 8 9]]


In [21]:
#Array indexing
#1D array
#import numpy as np
import array
a=array.array('i',[10,20,30,40,50])
print(a[0])
print(a[3])

10
40


In [22]:
#2D array
import numpy as np
a=np.array(([1,2,3],[4,5,6,],[7,8,9]))
print(a[0,0])
print(a[2,1])

1
8


In [18]:
import numpy as np
a=np.array([10,20,30,40,50,60])
print(a[1])
print(a[-1])
print(a[1:4])

20
60
[20 30 40]


In [27]:
import numpy as np
a=np.array(([1,2,3],[4,5,6,],[7,8,9]))
print(a[(0,1)])

2


In [8]:
#Boolean indexing
import numpy as np
a=np.array([10,20,30,40,50])
print(a[a>25])

[30 40 50]


In [7]:
#Fancy indexing
import numpy as np
a=np.array([10,20,30,40,50])
print(a[[1,3]])

[20 40]


In [4]:
#horizontal join
import numpy as np
a=np.array(([1,2],[3,4]))
b=np.array(([5,6],[7,8]))
print(np.hstack((a,b)))

[[1 2 5 6 7]
 [3 4 7 8 9]]


In [6]:
#vertical join
import numpy as np
a=np.array(([1,2],[3,4]))
b=np.array(([5,6],[7,8]))
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
#Depth join(O/P in next dimension)
import numpy as np
a=np.array(([1,2],[3,4]))
b=np.array(([5,6],[7,8]))
print(np.dstack((a,b)))

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [19]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(np.split(a,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [20]:
import numpy as np
a=np.array([1,2,3,4,5])
print(np.array_split(a,3))

[array([1, 2]), array([3, 4]), array([5])]
