In [4]:
import numpy as np
x=[20,40,50,70,10]
y=[6,2,9,7,1]
a=np.array(x)
b=np.array(y)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a.dot(b)) #Dot Product

[20 40 50 70 10]
[6 2 9 7 1]
[26 42 59 77 11]
[14 38 41 63  9]
[120  80 450 490  10]
[ 3.33333333 20.          5.55555556 10.         10.        ]
1150


In [7]:
#Scalar multiplication
import numpy as np
a=np.array([20,40,50,70,10])
b=3
print("Scalar:",b)
print("Array:",a)
print("Result:",a*b)

Scalar: 3
Array: [20 40 50 70 10]
Result: [ 60 120 150 210  30]


In [8]:
import numpy as np
a=np.array(([10,20],[30,40]))
b=np.array(([3,7],[5,9]))
print(a%b) #To display remainder

[[1 6]
 [0 4]]


In [10]:
def fn(x,y):
    if x>y:
        return x-y
    else:
        return x+y
a=[10,7,2]
b=[6,5,3]
vect_fn=np.vectorize(fn)
print("Array1:",a)
print("Array2:",b)
print("Result:",vect_fn(a,b))

Array1: [10, 7, 2]
Array2: [6, 5, 3]
Result: [4 2 5]
