In [2]:
# i) 3x4 array with random values
import numpy as np
a = np.random.random((3, 4))
print(a)



[[0.9159628  0.93147426 0.79375194 0.2339034 ]
 [0.0645958  0.01940346 0.60781927 0.08148167]
 [0.61907281 0.46434783 0.69425349 0.79503599]]


In [3]:
# ii) 3x4 array with zeros
import numpy as np
a = np.zeros((3, 4))
print(a)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# iii) Array with a range of even numbers
import numpy as np
a = np.arange(10, 34, 2)
print(a)



[10 12 14 16 18 20 22 24 26 28 30 32]


In [5]:
# iv) Array properties
import numpy as np
a = np.array([[1.1, 2.2, 3.3, 4.4], [5.5, 6.6, 7.7, 8.8], [9.9, 10.1, 11.1, 12.1]])
print("Dimensions:", a.ndim)
print("\nShape:", a.shape)
print("\nDatatype:", a.dtype)



Dimensions: 2

Shape: (3, 4)

Datatype: float64


In [6]:
# v) Flattening an array
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
