In [9]:
import numpy as np
a=np.array([1,6,2,7,6,4])
print(np.where(a==6))
print(np.where(a==7))

(array([1, 4]),)
(array([3]),)


In [11]:
import numpy as np
a=np.array([1,6,2,7,6,4])
print(np.where(a%2==0))
print(np.where(a%3==1))

(array([1, 2, 4, 5]),)
(array([0, 3, 5]),)


In [27]:
import numpy as np
a=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(a,8,side='left')
print(x)
print(a)

5
[0 1 2 2 7 8 9]


In [29]:
import numpy as np
a=np.array([9,5,2,7,6,4])
print(np.sort(a))
b=np.array(([7,4,9],[9,1,4]))
print(np.sort(b))

[2 4 5 6 7 9]
[[4 7 9]
 [1 4 9]]


In [37]:
import numpy as np
a=np.array([31,78,69,100])
x=[False,True,False,True]
b=a[x]
print(x)
print(b)
f=a>70
c=a[f]
print(f)
print(c)

[False, True, False, True]
[ 78 100]
[False  True False  True]
[ 78 100]


In [38]:
import numpy as np
a=np.array([31,78,69,100])
x=[False,False,False,False]
f=a>70
c=a[f]
print(f)
print(c)

[False  True False  True]
[ 78 100]
