In [1]:
import numpy as np
a=np.array([1,2,3,4])
print("One Dimensional array:",a)

One Dimensional array: [1 2 3 4]


In [2]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print("Two Dimensional array:",a)

Two Dimensional array: [[1 2 3 4]
 [5 6 7 8]]


In [5]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print("Three Dimensional array:\n",a)

Three Dimensional array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [6]:
import numpy as np
a=np.zeros((3,5))
print("One Dimensional array:\n",a)

One Dimensional array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
import numpy as np
a=np.random.random((2,2))
print("Random Value:\n",a)

Random Value:
 [[0.5951993  0.23473405]
 [0.27806647 0.4354547 ]]


In [8]:
import numpy as np
a=np.arange(0,60,5)
print("Sequence array:\n",a)

Sequence array:
 [ 0  5 10 15 20 25 30 35 40 45 50 55]


In [10]:
import numpy as np
a=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print("Original array:\n",a)
print("\nReshaped array:\n",a.reshape(4,3))

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original array:\n",a)
print("\nFlattened array:\n",a.flatten())

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened array:
 [1 2 3 4 5 6 7 8 9]


In [19]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Number of dimensions:",a.ndim)

Number of dimensions: 3


In [28]:
import numpy as np
a=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print("Shape of array:",a.shape)

Shape of array: (3, 4)


In [27]:
import numpy as np
a=np.array([1,2,3,4])
print("Array element type:",a.dtype)

Array element type: int64


In [31]:
import numpy as np
a=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print("Size of array:",len(a))

Size of array: 3


In [1]:
import numpy as np
a=np.array([1,2,3])
b=a.astype('float64')
print(a)
print(b)
print(b.dtype)

[1 2 3]
[1. 2. 3.]
float64
